[tool.poetry]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^1.0.1"
ruff = "^0.5.6"
tornado = "^6.4"
redis = "^5.0.3"
aiogram = "^3.4.1"
pipx = "^1.4.3"
httpx = "^0.27.0"
